# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.2.0.20260519"

package:
  name: types-decorator
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-decorator/types_decorator-${{ version }}.tar.gz
  sha256: b5b23b2f0d11c06748780697d345c8a684fc2d0c753f08ee8063660d9d7a23d9

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - package_contents:
      site_packages:
        - decorator-stubs/__init__.pyi
  - python:
      imports: []
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/python/typeshed
  summary: Typing stubs for decorator
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
